package P2P;


/**
* P2P/ClientRequestHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from p2p.idl
* Wednesday, February 10, 2016 6:13:40 PM EST
*/

abstract public class ClientRequestHelper
{
  private static String  _id = "IDL:P2P/ClientRequest:1.0";

  public static void insert (org.omg.CORBA.Any a, P2P.ClientRequest that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static P2P.ClientRequest extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (P2P.ClientRequestHelper.id (), "ClientRequest");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static P2P.ClientRequest read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClientRequestStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, P2P.ClientRequest value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static P2P.ClientRequest narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2P.ClientRequest)
      return (P2P.ClientRequest)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P2P._ClientRequestStub stub = new P2P._ClientRequestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static P2P.ClientRequest unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof P2P.ClientRequest)
      return (P2P.ClientRequest)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      P2P._ClientRequestStub stub = new P2P._ClientRequestStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
