package P2P;


/**
* P2P/ClientRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from p2p.idl
* Wednesday, February 10, 2016 6:13:40 PM EST
*/

public interface ClientRequest extends ClientRequestOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientRequest
