package P2P;

/**
* P2P/ClientRequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from p2p.idl
* Wednesday, February 10, 2016 6:13:40 PM EST
*/

public final class ClientRequestHolder implements org.omg.CORBA.portable.Streamable
{
  public P2P.ClientRequest value = null;

  public ClientRequestHolder ()
  {
  }

  public ClientRequestHolder (P2P.ClientRequest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P2P.ClientRequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    P2P.ClientRequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P2P.ClientRequestHelper.type ();
  }

}
