package P2P;


/**
* P2P/ClientRequestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from p2p.idl
* Wednesday, February 10, 2016 6:13:40 PM EST
*/

public interface ClientRequestOperations 
{
  String addFile (String fileName, String ip, String port);
  String removeFile (String fileName, String ip, String port);
  String searchFile (String fileName);
  String viewAllFiles ();
  String downloadFile (String fileName);
  String clearUploads (String ip, String port);
} // interface ClientRequestOperations
